### ISSUE TITLE
Ignorant checks

### ISSUE THREAD

**Issue by developer9998** [dyeddaboi/GTAntiCrash#1]
This is essentially cheating if you decide to use the Basement as intended:
- The master rightfully creating these bubbles is falsely flagged
- The bubbles will not appear, preventing the proper gimmick of the map

Bubbles are crucial for usage in Basement, to simply remove them is providing a... disadvantage ?  
This shouldn't be included at all, please actually know what you're doing.

**Comment by Loafiat** [comment]
it disables in basement? Did you even look into the code?

**Comment by Loafiat** [comment]
I feel like I should specify it disables the HARMONY PATCH in basement. I have checked myself, the bubbles work as intended and cause no issues in basement. I am looking into better ways to compare crash bubbles to intended bubbles.

**Comment by Loafiat** [comment]
Oh my god I just realized what you mean.

**Comment by Loafiat** [comment]
nvm I patched the local spawning it's fine 👍
